tokamak-network/tokamak-thanos

- packages/tokamak/contracts-bedrock/deploy-config/devnetL1-template.json
- packages/tokamak/contracts-bedrock/scripts/Deploy.s.sol
- packages/tokamak/contracts-bedrock/scripts/DeployConfig.s.sol
- packages/tokamak/contracts-bedrock/src/L1/OptimismPortal.sol
- packages/tokamak/contracts-bedrock/src/L1/token/TON.sol
Deploy TON for devnet deployment!
Thank you!
> Or 1273 fix the deploy script deploy ton in l1

- packages/tokamak/contracts-bedrock/scripts/verify-predeploy-contracts.sh
verify pre-deploy contracts script
thank you!
```bash
Verify L2 Pre-deploy contracts
Usage: /path/to/script/verify-predeploy-contracts.sh <ARGS>
Arguments:
-c, --chain-id        (required)               Set target chain id
-gURL, --genesis-url  (required)               Set genesis file for get contracts addresses
-eURL, --explorer-url (required)               Block explorer URL to verify contracts(only blockscout)
Example:
./verify-predeploy-contracts.sh \
--chain-id 111551115050 \
--genesis-url https://tokamak-titan-canyon.s3.ap-northeast-2.amazonaws.com/titan-sepolia-test/genesis.json \
--explorer-url https://explorer.titan-sepolia-test.tokamak.network
```
```bash
./packages/tokamak/contracts-bedrock/scripts/verify-predeploy-contracts.sh \           
--chain-id 111551115050 \ …
```
> Or 1335 create verify script pre deploy contracts in l2 using forge

- op-e2e/bridge_test.go
- op-service/sources/types.go
- add blockheader after Dencun
Thank you! 🙇🏼‍♂️
> [OR-1370] add blockheader after Dencun

- Makefile
- bedrock-devnet/devnet/__init__.py
- add devnet command for eth
There is a request to enable to test in eth.
So I added devnet command for eth
Thank you! 🙇🏼‍♂️
> [OR-1401] add devnet command for eth

- packages/tokamak/contracts-bedrock/test/CommonTest.t.sol
- packages/tokamak/contracts-bedrock/test/OptimismPortal.t.sol
Update testcases for test/OptimismPortal.t.sol
Thank you!
> Or 1330 titan canyon update test optimism portal.sol

- packages/tokamak/contracts-bedrock/test/CommonTest.t.sol
- packages/tokamak/contracts-bedrock/test/L1CrossDomainMessenger.t.sol
Update `L1CrossDomainMessger.t.sol` to match with the native token feature
> feat: OR-1342 update L1CrossDomainMessenger.t.sol

- packages/tokamak/contracts-bedrock/test/L1StandardBridge.t.sol
Testcase for L1StandardBridge in deposit cases
Thank you!
> Or 1328 titan canyon update test l1 standard bridge.t.sol in deposit cases

- Makefile
- bedrock-devnet/devnet/__init__.py
- packages/tokamak/contracts-bedrock/scripts/Deploy.s.sol
Fork the public network by using `anvil`
1. Create `.env` file
```sh
export FORK_PUBLIC_NETWORK=true
export L1_RPC='change me'
export FROM_BLOCK_NUMBER=19277372
export L2_NATIVE_TOKEN=0x2be5e8c109e2197D077D13A82dAead6a9b3433C5
export IMPL_SALT='change me'
```
2. Export these envs 
```sh
export $(xargs < .env)
``` 
3. Run
```sh
make devnet-up
```
> feat: OR-1389 fork public network

- packages/tokamak/contracts-bedrock/test/CommonTest.t.sol
- packages/tokamak/contracts-bedrock/test/L1CrossDomainMessenger.t.sol
- packages/tokamak/contracts-bedrock/test/L1StandardBridge.t.sol
- packages/tokamak/contracts-bedrock/test/OptimismPortal.t.sol
Testcases for L1StandardBridge in withdrawal cases
Thank you!
> Or 1329 titan canyon update test l1 standard bridge.t.sol in withdraw cases

- packages/tokamak/contracts-bedrock/scripts/verify-predeploy-contracts.sh
- Add thanos-sepolia-test
- Add TON & ETH verify code
> [OR-1408] add thanos-sepolia-test and L2 TON & ETH verify

- op-bindings/predeploys/addresses.go
notion : https://www.notion.so/Predeploy-contracts-in-L2-d55606770c1146838eefdb163e94cff9?d=a24dd4dd474049bf9440f21551f353ee&pvs=4#daeff162e3f647328420d83ae3c7b5c5
L2 ETH contract is not proxy but deploy with proxy
before :
ownerSlot(0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103)
implementSlot(0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc)
There are values(proxyAdmin, implement contract address) 
```
"4200000000000000000000000000000000000486": {
"code": "0x60806040526004361061005e5760003560e01c80635c60da1b116100435780635c60da1b146100be5780638f283970146100f8578063f851a440146101185761006d565b80633659cfe6146100755780634f1ef286146100955761006d565b3661006d5761006b61012d565b005b61006b61012d565b34801561008157600080fd5b5061006b6100903660046106dd565b6102245 …
```
> [OR-1424] change ETH contract not proxy

- .gitignore
- bedrock-devnet/devnet/__init__.py
- delete verfiy admin key 
- geth data gitignore
thank you!
> Or 1440 resolved devnet issue

- .github/workflows/release-docker-nightly.yml
- packages/tokamak/contracts-bedrock/scripts/verify-predeploy-contracts.sh
I changed this repository name from 'tokamak-titan-canyon' to 'tokamak-thanos'.
* create new s3 bucket: tokamak-thanos
* update secret: AWS_S3_BUCKET
* update path of release nightly docker CI
* update to new s3 bucket path in predeploys verify script
> change repository name

- op-e2e/portals_test.go
Add e2e tests for portals:
- go test -run TestDepositAndWithdrawSuccessfully
- go test -run TestOnApproveSuccessfully
- go test -run TestDepositAndCallL2Successfully
- go test -run TestDeployContractFailedNonPayableConstructor
- go test -run TestDeployContractFailedOutOfGas (test gas limit)
- go test -run TestDeployContractSuccessfully (estimate gas limit in case deposit contract on L2)
Thank you!
> Or 1505 titan canyon add e2e test for portals

- packages/tokamak/sdk/src/portals.ts
- packages/tokamak/sdk/tasks/deposit-withdraw-eth.ts
- packages/tokamak/sdk/tasks/deposit-withdraw-native-token.ts
- Fix  gas-used-calculation
- Add waitingDepositTransactionRelayedUsingL1Tx in Portal.
Thank you!
> Or 1503 titan canyon fix gas calculation in case gas scalar is a float

- .github/workflows/build.yml
- .github/workflows/check-go-lint.yml
- .github/workflows/check-ts-lint.yml
- .github/workflows/publish-tokamak-packages.yml
- .github/workflows/release-docker-nightly.yml
- .github/workflows/release-docker-release.yml
- .github/workflows/slither-check.yml
- .github/workflows/tokamak-contract-bedrock-test.yml
- ops/docker/Dockerfile.packages
Change Docker image from "titan-" to "thanos-"
Next step: change npm packages and folder in `titan-infra`
> feat: change docker image from titan to thanos

- op-e2e/calldata_builder_helper.go
- op-e2e/cross_domain_messenger_test.go
- op-e2e/portals_test.go
e2e test for CrossDomainMessenger
- go test -run TestSendNativeTokenMessageWithOnApprove
- go test -run TestCannotWithdrawTokenWithEmptyMessage: withdraw successfully on L2, cannot transfer token on L1
- go test -run TestDepositWithdrawalSendMessageSuccess
Thank you!
> Or 1291 add e2e test for cross domain messenger

- .github/workflows/release-docker-nightly.yml
- comment update-kustomize
I will uncomment this when we open new devnet (thanos-sepolia-nightly)
refer to: https://github.com/tokamak-network/tokamak-infra/pull/255
> [OR-1529] comment update-kustomize

- .github/workflows/release-docker-nightly.yml
- apply kustomiztion action
I tested it https://github.com/tokamak-network/tokamak-thanos/actions/runs/8703933202
> [OR-1536] apply update image for kustomization

- .github/workflows/slither-check.yml
- fix slither version problem
I checked this PR at the https://github.com/tokamak-network/tokamak-thanos/actions/runs/8735150491
Thank you!
I will merge main at the OR-1257 after merging this PR!
> [OR-1542] fix slither

- .github/workflows/slither-check.yml
- Merge slither to OR-1257
Thank you! ❤️
> Merge slither

- .github/workflows/build.yml
- .github/workflows/slither-check.yml
- .github/workflows/tokamak-contract-bedrock-test.yml
- change some action trigger (I think we have to check about entire PR about the specific tests)
@nguyenzung 
After checking this actions on OR-1257, I think we can merge main!
> [OR-1548] change some action trigger

- .github/workflows/publish-tokamak-packages.yml
Publish `@tokamak-network/core-utils` package to npm
> feat(workflows): publish @tokamak-network/core-utils to npm

- packages/tokamak/sdk/src/portals.ts
- packages/tokamak/sdk/tasks/portals.ts
Add getMessageStatus for Portals and examples 
Thank you!
> Or 1566 thanos cannon add get message status for portals

- .github/workflows/e2e-tests.yml
Update condition for running e2e test. Merge after: https://github.com/tokamak-network/tokamak-thanos/pull/151
Thank you!
> Or 1569 optimize spin up ec2 instances when creating pr to main

- .github/workflows/e2e-tests.yml
- .github/workflows/release-docker-nightly.yml
- .github/workflows/release-docker-release.yml
- .github/workflows/tokamak-contract-bedrock-test.yml
- change AWS account for ec2 runner!
I triggered s3 sync action (https://github.com/tokamak-network/tokamak-thanos/actions/runs/9015743344) for new AWS account
I triggered ec2 runner jobs in below
- e2e (https://github.com/tokamak-network/tokamak-thanos/actions/runs/9015743336)
- contract bedrock test (https://github.com/tokamak-network/tokamak-thanos/actions/runs/9015743335)
- publish nightly (https://github.com/tokamak-network/tokamak-thanos/actions/runs/9015743341)
Thank you!
> [OR-1583] migrate ec2 runner and s3

- packages/tokamak/sdk/src/interfaces/types.ts
- packages/tokamak/sdk/src/portals.ts
- packages/tokamak/sdk/tasks/portals.ts
- Update SDK for Portals: mint can be not equal to value
- Add a task as an example
Thank you!
> Or 1588 thanos cannon update sdk for new deposit transaction interface

- packages/tokamak/sdk/package.json
Release a new version of Thanos SDK to include the new code about `depositTransaction` function 
PR:https://github.com/tokamak-network/tokamak-thanos/pull/158
> feat(sdk): release v0.0.5

- Makefile
- bedrock-devnet/devnet/__init__.py
- op-batcher/Dockerfile
- op-challenger/Dockerfile
- op-heartbeat/Dockerfile
- op-node/Dockerfile
- op-program/Dockerfile
- op-proposer/Dockerfile
- op-wheel/Dockerfile
- ops-bedrock/docker-compose.yml
- change image name
Thank you! 🙇🏻‍♂️
> [OR-1605] change image name

- packages/tokamak/sdk/package.json
- packages/tokamak/sdk/src/portals.ts
- packages/tokamak/sdk/tasks/portals.ts
Add `estimateGas` to support to estimate the gas when interacting via Portal in Thanos SDK
> feat(sdk): add estimateGas in Portal

- ops/docker/Dockerfile.packages
- fix ci for publish docker pakcages
failed CI: https://github.com/tokamak-network/tokamak-thanos/actions/runs/9220157195
Thank you! 🙇🏼‍♂️
> [OR-1623] fix ci for publish docker pakcages

- op-exporter/go.mod
- op-ufm/go.mod
- proxyd/cmd/proxyd/main.go
- proxyd/go.mod
- change package name for other packages
Thank you very much! 🙇🏼‍♂️
> [OR-1625] change package name for other packages

- .github/workflows/release-docker-nightly.yml
- .github/workflows/release-docker-release.yml
- change instance to resolve docker build and push for ARM64
https://github.com/tokamak-network/tokamak-thanos/actions/runs/9255945602
Thank you!
> [OR-1626] change instance

- bedrock-devnet/devnet/__init__.py
Update `devnet` script to for Ecotone upgrade compatibility
> feat: update devnet script for Ecotone upgrade compatibility

- package.json
- packages/tokamak/sdk/package.json
- packages/tokamak/sdk/src/adapters/eth-bridge.ts
- packages/tokamak/sdk/src/adapters/standard-bridge.ts
- packages/tokamak/sdk/src/cross-chain-messenger.ts
- packages/tokamak/sdk/src/interfaces/types.ts
- packages/tokamak/sdk/src/l2-provider.ts
- packages/tokamak/sdk/src/utils/chain-constants.ts
- packages/tokamak/sdk/src/utils/coercion.ts
- packages/tokamak/sdk/src/utils/contracts.ts
- packages/tokamak/sdk/test-next/failedMessages.spec.ts
- packages/tokamak/sdk/test-next/messageStatus.spec.ts
- packages/tokamak/sdk/test-next/proveMessage.spec.ts
- packages/tokamak/sdk/test-next/testUtils/ethersProviders.ts
- packages/tokamak/sdk/test-next/testUtils/viemClients.ts
- packages/tokamak/sdk/test/contracts/MockMessenger.sol
- packages/tokamak/sdk/test/cross-chain-messenger.spec.ts
- packages/tokamak/sdk/tsconfig.json
- pnpm-lock.yaml
Following the Ecotone upgrade, I update our SDK source code.
Ref: https://github.com/ethereum-optimism/optimism/tree/develop/packages/sdk
I've tested some functionalities: deposit/withdraw eth/nativetoken/erc20
> feat(sdk): upgrade Ecotone SDK

- packages/tokamak/sdk/tasks/deposit-withdraw-native-token.ts
`l1FeeScalar` is undefined in the Ecotone version
> feat: remove l1FeeScalar in the hardhat task

- .github/workflows/build.yml
- .github/workflows/check-go-lint.yml
- .github/workflows/check-ts-lint.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/publish-tokamak-packages.yml
- .github/workflows/release-docker-nightly.yml
- .github/workflows/release-docker-release.yml
- .github/workflows/slither-check.yml
- .github/workflows/tokamak-contract-bedrock-test.yml
- Makefile
- bedrock-devnet/devnet/__init__.py
- op-batcher/Dockerfile
- op-bindings/bindgen/generator_local.go
- op-challenger/Dockerfile
- op-heartbeat/Dockerfile
- op-node/Dockerfile
- op-program/Dockerfile
- op-proposer/Dockerfile
- op-wheel/Dockerfile
- ops-bedrock/Dockerfile.l2
- ops-bedrock/docker-compose.yml
- ops/docker/Dockerfile.packages
- change docker repository
Thank you very much.
> [OR-1644] change docker repository

- .github/workflows/release-docker-nightly.yml
- update kustomize path
Thank you!
> [OR-1656] update kustomize path

- packages/tokamak/contracts-bedrock/scripts/go-ffi/bin.go
- packages/tokamak/contracts-bedrock/scripts/go-ffi/merkle.go
- packages/tokamak/contracts-bedrock/test/DisputeGameFactory.t.sol
- packages/tokamak/contracts-bedrock/test/FaultDisputeGame.t.sol
- packages/tokamak/contracts-bedrock/test/PreimageOracle.t.sol
Add and  fix tests that related to Fault Proof
Thank you!
> Or 1772 fault proof add unittest code for fault proof to a new branch called experiment

- .github/workflows/deposit-withdraw-test.yml
- op-e2e/Makefile
- op-e2e/e2e-dep-with/USDC_test.go
- op-e2e/e2e-dep-with/bridge_test.go
- op-e2e/e2e-dep-with/cross_domain_messenger_test.go
- op-e2e/e2e-dep-with/deposit_test.go
- op-e2e/e2e-dep-with/portal_test.go
ci:
https://github.com/tokamak-network/tokamak-thanos/actions/runs/10097346329/job/27921974113
> feat(ci): add deposit and withdrawal e2e tests

- .github/workflows/build.yml
- .github/workflows/check-ts-lint.yml
- .github/workflows/go-test.yml
- .github/workflows/publish-genesis-rollup.yml
- .github/workflows/publish-tokamak-packages.yml
- .github/workflows/release-docker-nightly.yml
- .github/workflows/release-docker-release.yml
- remove ec2 runner feature
https://github.com/tokamak-network/tokamak-thanos/actions/runs/10279559325
Thank you very much!
> [OR-1789] remove ec2 runner feature

- .github/workflows/build.yml
- .github/workflows/check-go-lint.yml
- .github/workflows/check-ts-lint.yml
- .github/workflows/deposit-withdraw-test.yml
- .github/workflows/go-test.yml
- .github/workflows/publish-tokamak-packages.yml
- .github/workflows/release-docker-nightly.yml
- .github/workflows/release-docker-release.yml
- .github/workflows/slither-check.yml
- .github/workflows/tokamak-contract-bedrock-test.yml
- indexer/Dockerfile
- ops/docker/Dockerfile.packages
- update thanos-ci-builder tag
I tested at https://github.com/tokamak-network/tokamak-thanos/actions/runs/10558069464
Thank you very much!
> [OR-1812] update thanos-ci-builder tag

- install-for-mac.sh
- homebrew
- git
- make
- Xcode Command Line Tools(Build-essential)
- Go (v1.22.6)
- Node.js (v20.16.0)
- NVM
- Pnpm
- Cargo (v1.78.0)
- Docker
- Foundry
> feat: Create shall script for macOS installation

- packages/tokamak/contracts-bedrock/hardhat.config.ts
- packages/tokamak/sdk/hardhat.config.ts
* contracts: removed thanos-sepolia-test in hardhat config 
* contracts, sdk: added thanos-sepolia in hardhat config
* fix lint
> add thanos-sepolia to hardhat config

- packages/tokamak/contracts-bedrock/README.md
- packages/tokamak/contracts-bedrock/scripts/Deploy.s.sol
- packages/tokamak/contracts-bedrock/src/L1/L1CrossDomainMessenger.sol
- packages/tokamak/contracts-bedrock/src/L1/L1StandardBridge.sol
- packages/tokamak/contracts-bedrock/src/L1/OptimismPortal2.sol
- packages/tokamak/contracts-bedrock/test/L1/OptimismPortal.t.sol
I updated README.md and comments for external audit requirement
* README.md in @tokamak-network/thanos-contracts
* update comments in L2 native token
* fix lint
> Or 1851 update readme and comments

- packages/tokamak/contracts-bedrock/genesis/thanos-sepolia/rollup.json
Set Fjord upgrade time to rollup.config
Upgrade time: Tue 29 Oct 09:00:01 GMT+09:00 (KST)
Thank you!
> [OR-1918] Thanos-sepolia fjord time set

- packages/tokamak/sdk/package.json
- packages/tokamak/sdk/src/utils/chain-constants.ts
Update the Thanos Sepolia configuration for our new testnet on Sepolia and release it.
> feat(sdk): update Thanos Sepolia addresses

- packages/tokamak/contracts-bedrock/scripts/start-deploy.sh
Support setting the gas price when the users want to increase the gas price to deploy the L1 contracts.
> feat(scripts): set gas price when deploying the L1 contracts

- go.mod
- go.sum
- op-node/rollup/derive/blob_data_source_test.go
- op-node/rollup/derive/calldata_source_test.go
- op-node/rollup/derive/data_source.go
- op-service/sources/types.go
- op-service/sources/types_test.go
Thanos Stack supports the Pectra hard fork on Ethereum
> feat: support Pectra hardfork

- install-devnet-packages.sh
- Source $SHELL_PROFILE before displaying messages
- Fix wrong profile path when installing the foundry
> fix: install foundry and reload the profile file after installing tools successfully

- install-devnet-packages.sh
- versions.json
I fixed some issues in devnet deployment. 
1. Docker installation: `/var/run/docker.sock: connect: permission denied error` 
2. Foundry installation: `not compile forge/anvil/cast` in foundry with memory leak
* Run docker daemon and change permission of docker socket after docker is installed
* Required foundry version: v1.0.0 (e144b82070619b6e10485c38734b4d4d45aebe04)
* Required rust version: v1.83.0
> Hotfix: update install devnet packages

- packages/tokamak/contracts-bedrock/scripts/start-deploy.sh
Reference: https://book.getfoundry.sh/reference/forge/forge-script
Option: `--resume`
> feat(script): resume deploying contracts

- packages/tokamak/contracts-bedrock/scripts/start-deploy.sh
To check whether artifacts are generated after building a contract and improve the build process robustly.
> Feat: Enhance deployment script with robust build and retry logic
