bedrock-devnet/devnet/__init__.py

Fix issue with newest geth by produce block for each 2 seconds. 
The current mode will produce new blocks when there are new transactions. 
Thank you!

OR-1409 add block period

---

bedrock-devnet/devnet/__init__.py
ops-bedrock/Dockerfile.l2
ops-bedrock/docker-compose.yml

- Using onthertech/titan-op-geth:nightly as default
- Support configurable L2_IMAGE to select docker image for op-geth
Thank you!

Or 1450 titan canyon update op geth docker image for devnet

---

op-e2e/bridge_test.go

Update e2e test for bridges: add withdrawal cases
Thank you!

OR-1525 update e2e-test for bridge

---

op-bindings/gen/main.go

Failed when running devnet with new generated-bindings (by cd op-bindings, "make" and start make devnet-up"
Fix: update bindings template file, refer to: https://github.com/tokamak-network/tokamak-thanos/blob/OR-1257-Update-smart-contracts-for-deposit-TON-in-L1/op-bindings/gen/main.go
I am not sure why the source map generator part was deleted. Please let me know if you have ideas.
Thank you very much!

OR-1534 update bindings template

---

ops-bedrock/Dockerfile.l2

I changed the name of l2 base image to onthertech/thanos-op-geth:nightly

OR-1559 change l2 base image name

---

packages/tokamak/sdk/src/adapters/native-token-bridge.ts

Use `depositNativeToken`function  when depositing the native token via the L1 Bridge

feat(sdk): use depositNativeToken instead of depositERC20 when depositing the native token via L1 Bridge

---

packages/tokamak/sdk/package.json

Release a new version of thanos-sdk to include Brave's [PR](https://github.com/tokamak-network/tokamak-thanos/pull/147):

feat: release @tokamak-network/thanos-sdk to v0.0.4

---

.github/workflows/e2e-tests.yml
.github/workflows/release-docker-nightly.yml
.github/workflows/release-docker-release.yml
.github/workflows/tokamak-contract-bedrock-test.yml

- Add timeout for EC2: we need to update the Shutdown behavior so EC2 instances will be terminated automatically after shutting down. 
- Make AWS role so that can change EC2 attribute setting
One remaining thing is: we still need to remove Github Runner config manually, because there is no support from machulav/ec2-github-runner@v2 to get Token to remove Runner, but we can fork this branch and make changed code. 
I tested on: https://github.com/tokamak-network/tokamak-thanos/tree/OR-1567-test
Thank you!

Or 1567 thanos cannon setup timeout for ec2 runner

---

packages/tokamak/sdk/src/adapters/standard-bridge.ts

When depositing ERC20, we don't need to set `nativeTokenAddress` in `CrossMessengerDomain`

feat(sdk): early return when the native token is undefined in StandardBridge

---

op-bindings/bindings/registry.go
op-bindings/predeploys/addresses.go
op-chain-ops/genesis/config.go
op-chain-ops/genesis/layer_two.go
op-chain-ops/immutables/immutables.go
op-chain-ops/immutables/immutables_test.go

Hello Everyone
I checked after the Thanos Ecotone update regarding UsdcBridge.
- changed the SignatureChecker's Deployedbytecode to include SignatureChecker's predeploy address. 
I think this is an inevitable process in Predeploy.
- changed immutables.go, immutables_test.go and config.go for MasterMinter's constructor.
- deleted the unrelated case statement from the l2ImmutableDeployer function.
- changed the layer_two.go because the implementation Address of FiatTokenProxy was not set.

Or 1621 check predeploys of usdc bridge

---

.github/workflows/build.yml

Ref to: https://github.com/ethereum-optimism/optimism/blob/develop/.circleci/config.yml#L171
I modified the `build` action to cache `go.mod`, and also built FPAC artifacts for the fault proofs feature.
Because this action is a built action(run `pnpm build`) so I want to trigger everytime the main branch is updated.

feat: cache go.sum and update build steps

---

op-bindings/hardhat/types.go

@AaronLee22 changed the type of `DeployedBytecode` from `[]byte` to `DeployedBytecode` struct in this [PR](https://github.com/tokamak-network/tokamak-thanos/pull/177/files#diff-38ab4d92d3f7c9f8e3c4446d1227ce60491adecf99c5b3477f368ef0d50d4852L20)
But we support both string and struct with this field. I faced the error when running `gotest` with the `op-bindings` folder because in the deployments this field is a string value.

fix(op-bindings): change type of DeployedBytecode to interface to support dynamic types

---

bedrock-devnet/devnet/__init__.py

In on-demand service, provide custom l2 chain id for devnet deploy.
when current scripts findig state-dump file that the file name is fixed state-dump-901.
So, check the chainid in deploy-config and proceed to the next step.

[OR-1842] feat: devnet custom L2 chain id

---

.github/dependabot.yml

Hello! 
We can use dependabot to check GitHub-action periodically and update it automatically.
This helps ensure that checks don't fail due to working version dismatch.
Thank you so much! ◡̎

Or 1861 automatic update of action version using dependabot

---

bedrock-devnet/devnet/__init__.py

When running `make devnet-test`, it will fail because we put the wrong params in Hardhat tasks
Refer: https://tokamak-network.slack.com/archives/C07HZARMSTD/p1728369793151639

fix(cmd): devnet test failed because putting wrong params in the Hardhat tasks

---

packages/tokamak/contracts-bedrock/src/L2/L2StandardBridge.sol

I removed require statement for checking whether this contract is paused in L2StandardBridge. 
* `paused()` function in L2StandardBridge always returns `false`. It means an unnecessary require statement was used. 
* This issue is reported from https://github.com/tokamak-network/tokamak-thanos/issues/271.

fix: remove calling paused in L2StandardBridge

---

packages/tokamak/sdk/package.json

I pump the version of SDK to 0.0.10. I made a mistake in creating a tag `0.0.9` last two months so the version of SDK right now is 0.0.9

feat(sdk): release v0.0.10

---

packages/tokamak/contracts-bedrock/package.json

The new version of SDK is using the latest version of contracts, so we should pump `@tokamak-network/contracts-bedrock` to a new version

feat(contracts-bedrock): release v0.0.5

---

packages/tokamak/contracts-bedrock/package.json

Release a new version of the Thanos contract to support changing the L1USDC bridge.

feat(contracts-bedrock): release v0.0.6

---

op-proposer/metrics/metrics.go
op-proposer/metrics/noop.go

updated the metrics to enable detection and monitoring by comparing the op-proposer account in the Fault Proof System (FPS) with external proposer accounts.
Thank you!

Or 1935 op challenger and op proposer metrics add prometheus alert rules

---

packages/tokamak/contracts-bedrock/deploy-config/thanos-stack-sepolia.json

I have completed the upgrade of the FaultDisputeGame contract.
However, instead of the proposed 6 seconds, I have changed it to 120 seconds.
Below is part of the constructor for the FaultDisputeGame contract.
```solidity
uint256 splitDepthExtension = uint256(_clockExtension.raw()) * 2;
uint256 maxGameDepthExtension = uint256(_clockExtension.raw()) + uint256(_vm.oracle().challengePeriod());
uint256 maxClockExtension = Math.max(splitDepthExtension, maxGameDepthExtension);
// The maximum clock extension must fit into a uint64.
if (maxClockExtension > type(uint64).max) revert InvalidClockExtension();
// The maximum clock extension may not be greater than the maximum clock duration.
if (uint64(maxClockExtension) > _maxClockDuration.raw()) revert InvalidClockExtension();
```
Based on the …

[OR-1983] Upgrade FaultDisputeGame: reduce ClockDuration to 120s

---

packages/tokamak/sdk/README.md

Deployed on the repository: https://github.com/tokamak-network/thanos-sdk-docs

feat(sdk): update the SDK docs domain

---

install-devnet-packages.sh
versions.json

1. We found the issue to be stuck contract deployment using Foundry v0.2.0. (But we cannot check the progress log while deployment) So we updated the version of dependencies. 
2. Add logic to change bash shebang according to O/S
Updated dependencies:
* Foundry: e144b82070619b6e10485c38734b4d4d45aebe04 (v1.0.0)
* Cargo: v1.83

Fix: Stuck to contact deployment

---

install-devnet-packages.sh

Fixed to separate version command on check_command_version() for zsh

fix: separate the version command using zsh

---

packages/tokamak/sdk/tasks/set-safe-for-dao.ts

I updated hardhat task: set-safe-wallet
* Use environment variables instead of arguments
* Error handling
* Fix lint
```bash
export PRIVATE_KEY=
export NATIVE_TOKEN=
export ADDRESS_MANAGER=
export L1_CROSS_DOMAIN_MESSENGER=
export L1_STANDARD_BRIDGE=
export OPTIMISM_PORTAL=
export L2_OUTPUT_ORACLE=
export SAFE_WALLET_ADDRESS=
export L1_URL=
export L2_URL=
```
Before:
```bash
npx hardhat set-safe-wallet --rpc ${L1_URL} --chainid ${L1_CHAINID} --privatekey ${ADMIN_PRIVATE_KEY} --address ${SAFE_WALLET_ADDRESS}
```
After:
```bash
npx hardhat set-safe-wallet
```

update hardhat task: set-safe-wallet

---

packages/tokamak/contracts-bedrock/foundry.toml
packages/tokamak/contracts-bedrock/scripts/Deploy.s.sol

It is related to https://github.com/tokamak-network/trh-sdk/issues/54. This change minimizes user confusion by avoiding displaying unnecessary logs while building the package '@tokamak-network/thanos-contracts'
```bash
> @tokamak-network/thanos-contracts@0.0.7 prebuild /Users/theo/workspace_tokamak/tokamak-thanos/packages/tokamak/contracts-bedrock
> ./scripts/checks/check-foundry-install.sh
Foundry version matches the expected version.
> @tokamak-network/thanos-contracts@0.0.7 build /Users/theo/workspace_tokamak/tokamak-thanos/packages/tokamak/contracts-bedrock
> forge build
[⠆] Compiling...
[⠰] Compiling 148 files with Solc 0.8.27
[⠔] Compiling 1 files with Solc 0.5.17
[⠒] Compiling 14 files with Solc 0.8.20
[⠑] Compiling 16 files with Solc 0.8.19
[⠘] Compiling 414 files with Solc 0.8.15 …
```

Chore: remove warning message while building contracts

---

packages/tokamak/sdk/src/adapters/usdc-bridge.ts
packages/tokamak/sdk/src/utils/contracts.ts

The forge 1.0.0 (e144b82070619b6e10485c38734b4d4d45aebe04) generates artifacts by compiler version according to the dependency using `forge build` command. This PR is for resolving build errors by reflecting changes in @tokamak-network/thanos-sdk.
* Related issue: https://github.com/tokamak-network/trh-sdk/issues/67

fix: cannot find artifact of L1UsdcBridge while building @tokamak-network/thanos-sdk

---

op-chain-ops/genesis/config.go
packages/tokamak/contracts-bedrock/deploy-config/devnetL1-template.json
packages/tokamak/contracts-bedrock/scripts/Deploy.s.sol
packages/tokamak/contracts-bedrock/scripts/DeployConfig.s.sol

Thanos Stack Optimization: I updated L1 deployment script to save resources such as gas fees and deployment time. The changed logic only applies when L2 is deployed more than twice on the same network (it is called “duplicate deployment”) The other case is called “initial deployment”.
1. Gas: About 50% reduced (80053913 -> 42637728)
2. The number of txns while deployment: about 20% reduced (62 -> 51)
1. Required new deploy config field: `reuseDeployment`. If true, we allow to re-use deployment. If false, all implementations and proxies are distributed without reuse.
2. When it is duplicate deployment, it load deployed addresses from JSON specified in advance during proxy initialization phase and use it.
3. Add `verifyImplementationExists()`: This function is to verify if the …

Feat: skip redundant implementation deployment
